import { motion } from 'motion/react';
import { Share2, Twitter, Instagram } from 'lucide-react';

interface ColorSwatchProps {
  color: string;
  pantoneCode: string;
  pantoneName: string;
  prompt: string;
}

export function ColorSwatch({ color, pantoneCode, pantoneName, prompt }: ColorSwatchProps) {
  const shareText = `Check out this perfect color: ${pantoneName} (${color}) - generated by i really need a color swatch!`;
  const shareUrl = window.location.href;

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${pantoneName} - Perfect Color`,
          text: shareText,
          url: shareUrl,
        });
      } catch (err) {
        console.log('Error sharing:', err);
      }
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(`${shareText} ${shareUrl}`);
      alert('Color details copied to clipboard!');
    }
  };

  const handleXShare = () => {
    const xUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`;
    window.open(xUrl, '_blank');
  };

  const handleInstagramShare = () => {
    // Instagram doesn't support direct sharing, so we'll copy the text
    navigator.clipboard.writeText(`${shareText} ${shareUrl}`);
    alert('Color details copied! Paste this in your Instagram story or post.');
  };

  const handleTikTokShare = () => {
    // TikTok doesn't support direct sharing, so we'll copy the text
    navigator.clipboard.writeText(`${shareText} ${shareUrl}`);
    alert('Color details copied! Paste this in your TikTok video description.');
  };
  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 1.2, ease: "easeOut" }}
      className="flex flex-col items-center gap-4 mt-4"
    >
      {/* Color Card */}
      <motion.div 
        className="bg-white border-2 border-black overflow-hidden"
        style={{ width: '300px' }}
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 1.0, delay: 0.3, ease: "easeOut" }}
      >
        {/* Color Block - Perfect Square */}
        <div 
          style={{ 
            width: '300px', 
            height: '300px',
            backgroundColor: color 
          }}
        />
        
        {/* Color Information Panel */}
        <div className="bg-white p-3 space-y-2">
          {/* Color Name */}
          <div className="space-y-1">
            <h3 className="text-base font-medium text-black">
              {pantoneName}
            </h3>
            <p className="text-xs text-black font-mono uppercase tracking-wide">
              {pantoneCode.replace('PANTONE ', '')}
            </p>
          </div>
          
          {/* Color Values */}
          <div className="space-y-1 pt-2 border-t-2 border-black">
            <div className="flex justify-between">
              <span className="text-xs font-medium text-black uppercase tracking-wide">
                HEX
              </span>
              <span className="text-xs font-mono text-black">
                {color.toUpperCase()}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-xs font-medium text-black uppercase tracking-wide">
                RGB
              </span>
              <span className="text-xs font-mono text-black">
                {(() => {
                  const hex = color.replace('#', '');
                  const r = parseInt(hex.substring(0, 2), 16);
                  const g = parseInt(hex.substring(2, 4), 16);
                  const b = parseInt(hex.substring(4, 6), 16);
                  return `${r}, ${g}, ${b}`;
                })()}
              </span>
            </div>
          </div>
        </div>
      </motion.div>
      
      {/* Sharing Buttons */}
      <motion.div 
        className="flex items-center gap-3 mt-2"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.8, delay: 0.8 }}
      >
        <button
          onClick={handleShare}
          className="flex items-center gap-2 px-3 py-2 bg-white text-black text-xs font-medium border-2 border-black hover:bg-gray-100 transition-colors duration-200"
        >
          <Share2 className="w-3 h-3" />
          Share
        </button>
        <button
          onClick={handleXShare}
          className="flex items-center gap-2 px-3 py-2 bg-white text-black text-xs font-medium border-2 border-black hover:bg-gray-100 transition-colors duration-200"
        >
          <Twitter className="w-3 h-3" />
          X
        </button>
        <button
          onClick={handleInstagramShare}
          className="flex items-center gap-2 px-3 py-2 bg-white text-black text-xs font-medium border-2 border-black hover:bg-gray-100 transition-colors duration-200"
        >
          <Instagram className="w-3 h-3" />
          Instagram
        </button>
        <button
          onClick={handleTikTokShare}
          className="flex items-center gap-2 px-3 py-2 bg-white text-black text-xs font-medium border-2 border-black hover:bg-gray-100 transition-colors duration-200"
        >
          <span className="w-3 h-3 text-xs font-bold">T</span>
          TikTok
        </button>
      </motion.div>

      {/* Inspiration Credit */}
      <motion.div 
        className="text-center"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.8, delay: 1.0 }}
      >
        <p className="text-xs text-white opacity-80">
          inspired by "{prompt}"
        </p>
      </motion.div>
    </motion.div>
  );
}